[project]
name = "n-body-sim"
version = "0.1.0"
description = "Bonjour"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["numpy", "matplotlib"]

[tool.uv.workspace]
members = [
    "test",
]
